### ISSUE TITLE
Issue with

### ISSUE THREAD

**Issue by alazare619** [mdhiggins/sonarr-sma#1]
Running the below config. 
Post sonarr is running
Path: /usr/local/bin/sma/env/bin/python3
Arguments: /usr/local/bin/sma/sickbeard_mp4_automator/postSonarr.py

Below is my sonarr-sma
```
Mount 1: /nzbget-downloads:/nzbget-downloads
Mount 2: /media:/media
Mount 3: /docker-appdata/mp4-automator/autoProcess.ini:/usr/local/bin/sma/sickbeard_mp4_automator/autoProcess.ini
Mount 4: /docker-app-data/linuxserver-sonarr:/config
```

Here is my lsio-nzbget
```
Mount 1: /nzbget-downloads:/nzbget-downloads
Mount 2: /docker-app-data/linuxserver-nzbget:/config
```
autoProcess.ini
```
[Sonarr]
host = 192.168.1.253
port = 8989
web_root = 
ssl = False
apikey = 651dcfdd456446b0acdeb0bc52587d0c

[MP4]
ffmpeg = /usr/local/bin/ffmpeg/ffmpeg
ffprobe = /usr/local/bin/ffmpeg/ffprobe
threads = 0
output_directory = 
copy_to = 
move_to = 
output_extension = mp4
output_format = mp4
delete_original = True
relocate_moov = True
video-codec = h264,x264
video-bitrate = 
video-crf = 
video-max-width = 
video-profile = 
h264-max-level = 
use-qsv-decoder-with-encoder = True
use-hevc-qsv-decoder = False
enable_dxva2_gpu_decode = False
ios-audio = True
ios-first-track-only = False
ios-audio-filter = 
ios-move-last = False
max-audio-channels = 
audio-codec = aac
audio-language = 
audio-default-language = 
audio-channel-bitrate = 128
audio-filter = 
audio-copy-original = False
audio-first-track-of-language = False
subtitle-codec = mov_text
subtitle-language = 
subtitle-default-language = 
subtitle-encoding = 
fullpathguess = True
convert-mp4 = False
tagfile = True
tag-language = en
download-artwork = Poster
download-subs = False
embed-subs = True
embed-only-internal-subs = False
sub-providers = addic7ed,podnapisi,thesubdb,opensubtitles
permissions = 0777
post-process = False
pix-fmt = 
aac_adtstoasc = False
postopts = 
preopts = 
```

Do I need to run the nzbget  post process script as well?
Reason I ask is because the LSIO nzbget doesnt have python by default added.

Below are errors in sonarr's log
```
19-3-9 05:46:18.6|Error|python3|Traceback (most recent call last):
19-3-9 05:46:18.6|Error|python3|  File "/usr/local/bin/sma/sickbeard_mp4_automator/postSonarr.py", line 39, in <module>
19-3-9 05:46:18.6|Error|python3|    season = int(os.environ.get('sonarr_episodefile_seasonnumber'))
19-3-9 05:46:18.6|Error|python3|TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Comment by alazare619** [comment]
@mdhiggins any idea whats going on with this? The python error i believe can be ignored I had it set on grab to fire too. But running top inside the container i'm never seeing FFMPEG show up. The mono process does start using more memory but thats about it.

**Comment by alazare619** [comment]
after setting nzbdrone/sonarr to completed download handling its working but now im having the issue of its not queing episodes it shows that ffprobe checked them but it looks like they are just downloading faster then they can postsonarr convert. is there a queing mechanism that should be working?

**Comment by mdhiggins** [comment]
Sonarr should handle that the script doesn't directly queue, there shouldn't be a thing with downloading too fast, what issues are you seeing? are some files getting converted and not others? and can you post some logging info

**Comment by danielpetrovic** [comment]
I am having the same error, I have set the 'Connect' option to:
On Download and On Rename, or is that not supported?
When I try to rename files it doesn't run at all, so no conversion happens.

When I try to run manual.py it does work.

It is running in Docker on a Synology DS918+ with DSM 6.2.2, but that shouldn't make a difference right?

[edit]
The On Complete handling does seem to work. So I guess On Rename is not supported?

**Comment by mdhiggins** [comment]
Should be 'On Download' and 'On Upgrade'
