### ISSUE TITLE
Plex standard config

### ISSUE THREAD

**Issue by powerdude** [mdhiggins/sonarr-sma#11]
Hi,

Sorry to add this non-issue here, but do you have a standard config file, or a recommendation of settings, that just "work" to give you a great video file for Plex?  I'm not a huge videophile and I'm not into the technical weeds of video, just want to convert files that work without Plex doing any unnecessary work when i use it from my TV, PC, phone or tablet.

**Comment by mdhiggins** [comment]
The default settings are sort of targeted for that exact use, so if you just configure your ffmpeg/ffprobe path and leave all the other settings that'll get you pretty much what you want
