### ISSUE TITLE
Both sonarr-sma & radarr-sma

### ISSUE THREAD

**Issue by djrarky** [mdhiggins/sonarr-sma#15]
When running manual.py, get the error

root@e3dcba9759e7:~# /usr/local/sma/manual.py 
Traceback (most recent call last):
  File "/usr/local/sma/manual.py", line 5, in <module>
    import guessit
ModuleNotFoundError: No module named 'guessit'

**Comment by mdhiggins** [comment]
This is a super generic python error for not having a module installed, in your case guessit

**Comment by mdhiggins** [comment]
Wait just realized this was on the docker container, you need to use the python virtual environment, you can't just execute the file directly

`$SMA_PATH/venv/bin/python3 $SMA_PATH/manual.py`
