### ISSUE TITLE
Unable to send OnDownload notification

### ISSUE THREAD

**Issue by Zeusy123** [mdhiggins/sonarr-sma#16]
Hi Higgins, 

After using:
docker build https://github.com/mdhiggins/sonarr-sma.git#build --build-arg ffmpeg_tag=4.2-ubuntu --build-arg sonarr_tag=preview

To build sonarr preview image with ffmpeg (libfdk_aac) codec

When i miport an episode it fails with sonarr event:

Unable to send OnDownload notification to: Mp4 Automator: ApplicationName='/usr/local/sma/postSonarr.sh', CommandLine='', CurrentDirectory='', Native error= Access denied

So I double check the permissions on the postSonarr.sh file within the image.
When i make postSonarr.sh writable the error goes away until the image is update again.

-rw-r--r-- 1 root root    72 Nov  2 11:25 postSonarr.sh

Just wondering is the a way to ensure when image is updated that the file states writable?

**Comment by mdhiggins** [comment]
I would just use a different filename to not interfere with the routine process. just name is something like customPostSonarr.sh and point Sonarr to that file instead

**Comment by mdhiggins** [comment]
Additionally when you do make your new file you need to give it execute permissions, that's where your error is coming from

**Comment by Zeusy123** [comment]
Thats works great im nearly there:)

Would it be possible to make a copy of the source file sent from sonarr to a fixed location?
Maybe editing the postsonarr.sh?
So copy sourcefile to /720import/ folder, before your encoding starts?

**Comment by mdhiggins** [comment]
Yeah you could easily just add a line to postSonarr.sh to copy a file using usual operating system commands

**Comment by mdhiggins** [comment]
https://github.com/Sonarr/Sonarr/wiki/Custom-Post-Processing-Scripts

Those are all the environment variables sonarr passes so you can use them too

**Comment by Zeusy123** [comment]
Thanks bro,  Im no coder, but I try:)

so if i change contents my_postsonarr.sh file too:
-------
`#!/usr/bin/env bash

$replace = array(
'1280 Series' => '720 Series',
'test1' => 'test2'
'testa' => 'testb'
);

function strReplaceAssoc(array $replace, $filePath) {
   return str_replace(array_keys($replace), array_values($replace), $filePath);   
}

cp "$filePath" "str_replace_assoc($replace,$filePath);"

$SMA_PATH/venv/bin/python3 $SMA_PATH/postSonarr.py`
---------------
Will this work?? 

orginal path: /tv/1280 Series/Mandalorian, The/Season 1/testing.mkv

copy "/tv/1280 Series/Mandalorian, The/Season 1/testing.mkv" "/tv/720 Series/Mandalorian, The/Season 1/testing.mkv"
When completed. then execute your : $SMA_PATH/postSonarr.py
