### ISSUE TITLE
making it copy source file before encoding

### ISSUE THREAD

**Issue by Zeusy123** [mdhiggins/sonarr-sma#17]
Im trying to generate a copy of the source file from sonarr to another location, BEFORE encoding via mp4 automator.
I've edited the postsonarr.sh file as the following and gave write permissions etc.. but still fails:( recking my head on it and i know im doing something stupid.  please can  u see why it wont work?

my_postsonarr.sh
```
#!/usr/bin/env bash

file='$sonarr_episodefile_sourcepath'
dest='/downloads/backup/'

cp $file $dest

$SMA_PATH/venv/bin/python3 $SMA_PATH/postSonarr.py
```
Thankyou in advance.

**Comment by mdhiggins** [comment]
Try

```
#!/usr/bin/env bash

cp $sonarr_episodefile_path /downloads/backup

$SMA_PATH/venv/bin/python3 $SMA_PATH/postSonarr.py
```

And you need to make sure /downloads/backup exists and has write permissions

**Comment by mdhiggins** [comment]
Please continue this discussion on the old issue, as its not an issue with the script and is actually unrelated to the script entirely, you're essentially just looking for assistance on how to make a sonarr post processing script
