### ISSUE TITLE
Update build using args

### ISSUE THREAD

**Issue by Zeusy123** [mdhiggins/sonarr-sma#18]
Hi there, just want to say a huge thankyou for all your hard word, it is truly appreciated and the scripts are amazing:)
I have achieved what i need your brilliant scripts todo:)

As you sujested to make an image with sonarr/sma v3 version with ffmpeg version using --enable-libfdk_aac

docker build https://github.com/mdhiggins/sonarr-sma.git#build --build-arg ffmpeg_tag=4.2-ubuntu --build-arg sonarr_tag=preview

There has been numerous update on sonarr since i built this image last week, so Im just wondering the comman so i can force an update of your image ,but keep all the fuctionablilty of v3 sonarr and the correct version of ffmpeg?

**Comment by mdhiggins** [comment]
Just rebuild using the same args
