### ISSUE TITLE
Any plans to upgrade the sonarr container

### ISSUE THREAD

**Issue by sbergwall** [mdhiggins/sonarr-sma#20]
First of all, thank you for your work! 

Do you have any plans to upgrade to sonarr container to a newer version of the phantom-develop release build?

**Comment by mdhiggins** [comment]
The container is based on https://registry.hub.docker.com/r/linuxserver/sonarr so it would need to be something they include first

**Comment by sbergwall** [comment]
Thank!

**Comment by mdhiggins** [comment]
If they happen to add that branch/tag and I haven't updated my container feel free to ping me or open this back up and I'll take care of it

**Comment by joryirving** [comment]
I was running the preview tag, and noticed it hadn't updated in a while. I see that linuxserver deprecated the preview tag, as the latest tag now uses v3. Not sure if you want to update/remove/document the preview tag for your container?

**Comment by mdhiggins** [comment]
@LilDrunkenSmurf 

Removed the preview branch and added a new develop branch/tag
Build successful
https://hub.docker.com/layers/mdhiggins/sonarr-sma/develop/images/sha256-68a78c1c1eb4c9c5261acc48a17f7c8f238aafa9344206b90a58a770e1040cec?context=repo
