### ISSUE TITLE
FFMPEG-VAAPI

### ISSUE THREAD

**Issue by gresheff** [mdhiggins/sonarr-sma#23]
Thanks for all of your great work on this project!
I am a bit of a noob so please excuse me if my comments are too ambiguous.

I have been trying to use sonarr-sma and radarr-sma containers to transcode with VAAPI hardware acceleration (jrottenberg static images).  I have been using the #build tag as per the README.  This has worked well with radarr-sma but there are missing dependencies for sonarr-sma which causes ffmpeg to fail.

I believe the reason may be that the ffmpeg VAAPI binaries have been based off focal.  Radarr has recently been rebased to focal which is why the multi stage build works (with all required dependencies).  Sonarr is still on a bionic base (mono) and therefore there are missing dependencies.

**Comment by mdhiggins** [comment]
Does rolling back to bionic for sonarr on the jrottenberg side of things make any difference? I believe I tested it on bionic with mono and it worked fine

Its mentioned in the readme you should try and match the versions for compatibility

**Comment by mdhiggins** [comment]
`4.3.2-vaapi1804` as your `ffmpeg_tag` specifically

**Comment by gresheff** [comment]
That did it, thanks!
  
Wasn’t aware you could pull older binaries with this kind of tagging.
  
  
  

  

  
  
  
  

  
  
>

**Comment by mdhiggins** [comment]
So you're not actually even pulling an old binary. The jrottenberg container is building FFMPEG from source and you're just changing the build environment using docker tags and then copying the binaries from one container to another. Its the latest version of FFMPEG
