### ISSUE TITLE
SonarrPostProcess - ERROR - Unable to restore scene information.

### ISSUE THREAD

**Issue by CanisHelix** [mdhiggins/sonarr-sma#25]
I have switched over to user sonarr-sma since yesterday and I am seeing the following error for multiple conversions in my sma.log file. Is this something to be concerned about or safe to ignore?

```
2021-06-04 05:12:49 - SonarrPostProcess - ERROR - Unable to restore scene information.
Traceback (most recent call last):
  File "/usr/local/sma/postSonarr.py", line 281, in <module>
    mf = getEpisodeFile(baseURL, headers, sonarrepinfo['episodeFile']['id'], log)
KeyError: 'episodeFile'
2021-06-04 05:12:49 - SonarrPostProcess - INFO - Sonarr response RenameSeries command: ID <redacted> queued.
```

**Comment by mdhiggins** [comment]
This is fixed, was a recent addition and the error won't interfere with anything but should be fixed anyway. 

That being said the ability to restore the scene information hasn't been incorporated into the latest develop build of Sonarr yet (I wrote the pull request) though its working for Radarr

**Comment by CanisHelix** [comment]
Thanks for the fix and confirmation that it doesn't matter yet.

**Comment by mdhiggins** [comment]
Just to confirm restoring the scene information is now working in developer branch of Sonarr and the latest version of SMA
