### ISSUE TITLE
ffmpeg error?

### ISSUE THREAD

**Issue by Zeusy123** [mdhiggins/sonarr-sma#28]
Hi bro, just did a new build using:

docker build https://github.com/mdhiggins/sonarr-sma.git#build --build-arg ffmpeg_tag=4.4-ubuntu --build-arg sonarr_tag=preview

I need the libfdk_aac in ffmpeg build is the must have.

all compiled ok and runs...but when i run the ffmpeg command on console i get:

root@b2a58463d15a:/# whereis ffmpeg
ffmpeg: /usr/local/bin/ffmpeg
root@b2a58463d15a:/# ffmpeg
ffmpeg: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /usr/local/lib/libavdevice.so.58)
ffmpeg: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/local/lib/libavfilter.so.7)
ffmpeg: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /usr/local/lib/libavformat.so.58)
ffmpeg: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/local/lib/libavcodec.so.58)
ffmpeg: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/local/lib/libswresample.so.3)
ffmpeg: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/local/lib/libswscale.so.5)
ffmpeg: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/local/lib/libavutil.so.56)
ffmpeg: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /usr/local/lib/libavutil.so.56)
ffmpeg: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/local/lib/libvmaf.so.1)
ffmpeg: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/local/lib/libass.so.9)
ffmpeg: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/local/lib/libvidstab.so.1.1)
ffmpeg: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/local/lib/libsrt.so.1)
ffmpeg: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/local/lib/libvpx.so.6)
ffmpeg: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/local/lib/libaom.so.0)
ffmpeg: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/local/lib/libfdk-aac.so.1)
ffmpeg: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/local/lib/libmp3lame.so.0)
ffmpeg: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/local/lib/libopenjp2.so.7)
ffmpeg: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/local/lib/libopus.so.0)
ffmpeg: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/local/lib/libvorbis.so.0)
ffmpeg: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/local/lib/libwebp.so.7)
ffmpeg: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/local/lib/libx264.so.148)
ffmpeg: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/local/lib/libx265.so.192)
ffmpeg: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/local/lib/libxvidcore.so.4)
ffmpeg: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/local/lib/libkvazaar.so.6)
ffmpeg: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/local/lib/libxml2.so.2)
ffmpeg: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/local/lib/libpng16.so.16)
root@b2a58463d15a:/# 

any idea why or how to fix please and thankyou once again for your great work??

**Comment by Zeusy123** [comment]
Anyone any idea? days now searching and no fix:(  looks like i will have to goto back to older version:(

**Comment by Zeusy123** [comment]
Hello!! anyone idea how solution to the above???

Server is Ubuntu 18.04.5 LTS
using protainer to manage dockers.

**Comment by mdhiggins** [comment]
Try matching the ubuntu versions of your 2 containers, this has been covered in other issues before

the `preview` sonarr tag from linuxserver is on focal (2004) and the default nvidia tag for ffmpeg is still on 1804

So change your nvidia tag to `4.4-ubuntu2004`

**Comment by Zeusy123** [comment]
Mdhiggins, thankyou for your help, on same day i finally managed to figure it, I ran:

docker build https://github.com/mdhiggins/sonarr-sma.git#build --build-arg ffmpeg_tag=4.3-ubuntu1804 --build-arg sonarr_tag=preview

worked perfectly:)
