### ISSUE TITLE
Container not updated

### ISSUE THREAD

**Issue by kevindd992002** [mdhiggins/sonarr-sma#3]
I was under the impression that when the linuxserver\sonarr container gets updated, your container gets updated too because it is based off of that container. Is this not accurate? Or do you always have to do it manually? Here's what I see in the Updates page in Sonarr:

![image](https://user-images.githubusercontent.com/3907957/63988452-ed233900-cb0e-11e9-838b-5497171cb673.png)

I see that your container was last updated two months ago which explains why it doesn't have the lastest Sonarr version.

**Comment by kevindd992002** [comment]
@mdhiggins , are you monitoring this?

**Comment by kevindd992002** [comment]
Following up on this please.

**Comment by kevindd992002** [comment]
@mdhiggins can you help me out here please? I just need to know if will you really abandoned this container alteady or continue maintaining it? If the former, I'll try using the latest version of your script in my host instead of this outdated container.

**Comment by mdhiggins** [comment]
Just rebuilt it
Apparently docker hub does not automatically rebuild when parent containers are updated
You can always take the docker file and build it yourself

**Comment by kevindd992002** [comment]
Correct, it doesn't really do it. I haven't really tried rebuilding using a dockerfile though. I just use watchtower to automatically update containers if they have new version i docker hub.

**Comment by kevindd992002** [comment]
Rebulding it using the dockerfile would also update the script itself, right?
