### ISSUE TITLE
Learning and need help with installation

### ISSUE THREAD

**Issue by ikrowni** [mdhiggins/sonarr-sma#30]
Hello I'm using docker desktop on windows and having some trouble getting set up. 

It says for me to use NVENC I should choose the jrottenberg/ffmpeg's method which I got installed but I'm running into a problem getting Prowlarr to connect with Sonarr since the 'build' version is using Sonarr v2. 

When I was using the "latest" version it was on v3 and I had no issues connecting with Prowlarr. I want to be able to use my GPU though so that's why I'm trying to migrate over to this build.

**Comment by mdhiggins** [comment]
Just change your `sonarr-tag` if you need to use the develop version

Also make sure you're building that image locally and not using the super old placeholder image that's up from like 8 months ago, its meant to be built locally, the image is not meant to be pulled down from the repo

**Comment by mdhiggins** [comment]
Went ahead and deleted the old placeholder builds to avoid confusion

**Comment by ikrowni** [comment]
> Also make sure you're building that image locally

I'm sorry I'm really really new to using docker could you explain what I need to do to do that? It's no problem if you don't have time I can  just keep reading to try and figure it out.

```
docker run -ti ^
    --name=sonarr ^
    --restart unless-stopped ^
    -v E:/Share/_Docker_/SONARR/sma/:/usr/local/sma/config ^
    -v E:/Share/_Docker_/SONARR/sonarr:/config ^
    -v E:/Share/TV/:/tv ^
    -v E:/Share/_Downloads_/sonarr/:/downloads ^
    -p 8989:8989 ^
    -e PUID=${PUID} ^
    -e PGID=${PGID} ^
    mdhiggins/sonarr-sma:develop
```

like this or do i actually have to build the program myself?

**Comment by mdhiggins** [comment]
You'll definitely need to read up on docker more but the basics are that you're not pulling an image and running it as above, but instead building it from the dockerfile locally and providing your own arguments then running

https://docs.docker.com/engine/reference/commandline/build/

```
docker build https://github.com/mdhiggins/sonarr-sma.git#build --build-arg ffmeg_tag=nvidia2004 --build-arg sonarr_tag=develop
```
