### ISSUE TITLE
kubernetes

### ISSUE THREAD

**Issue by jameseck** [mdhiggins/sonarr-sma#41]
I see that ffmpeg is not baked into the image, it's downloaded each time you run the image.
This might work fine within docker, but with kubernetes, it's a bit of a problem.  It takes a long time to download ffmpeg and within this time, kubernetes kills the container and restarts it.  I could probably work around this by modifying the startup probe to allow it long enough for the ffmpeg downloads, but downloading ffmpeg every time the container restarts is going to result in a poor experience.

Is there a chance of getting an image with ffmpeg baked in?
Failing that, an option to have ffmpeg downloaded to a volume instead of just /usr/local/bin/ would allow the first container start to download ffmpeg and subsequent starts could reuse the existing ffmpeg in the volume.

**Comment by mdhiggins** [comment]
It's only downloaded on first launch/freshly created containers not every time the container starts (unless you're recreating the container on every restart for some reason)

It used to be baked in but there was issues with the main providers blocking the download from GitHub causing the build to fail

You can easily mount an FFMPEG/ffprobe binary it only tries to download if it's not there
