### ISSUE TITLE
Script exited with error code: 1

### ISSUE THREAD

**Issue by hroman73** [mdhiggins/sonarr-sma#42]
I recently noticed that my files were not being processed. When I run a test on the postSonarr.sh under connection I get "Script exited with error code: 1"

**Comment by hroman73** [comment]
I also checked radarr and it is also having the same error.

both are the docker versions...

**Comment by mdhiggins** [comment]
Gonna need more info from the logs to give you any meaningful help

**Comment by mdhiggins** [comment]
Just did a fresh pull and its working fine on my end

**Comment by hroman73** [comment]
I also did a new pull and it did refresh the two containers and it is now working again, thank you...
