### ISSUE TITLE
Latest stable version of sonaar v3.0.9.1549

### ISSUE THREAD

**Issue by Zeusy123** [mdhiggins/sonarr-sma#43]
Hi bro, Im using below line to build image.
docker build https://github.com/mdhiggins/sonarr-sma.git#build --build-arg ffmpeg_tag=5.1-ubuntu1804

However this sonarr version is 3.0.8.1507
Anyways to force it to use the latest stable build??

Thanks in advance.

**Comment by mdhiggins** [comment]
Sonarr version is based on the parent container from linuxserver, not sure what their latest image is using but it might be that

Can try switching to develop branch using `sonarr_tag`

**Comment by Zeusy123** [comment]
Thanks for the quick reply

https://hub.docker.com/r/linuxserver/sonarr

is using latest version.   [3.0.9.1549-ls161]

I need to use #build as I need ffmpeg to have codec  i require.

**Comment by mdhiggins** [comment]
The default sonarr tag is latest so it should match up with linuxserver

ARG sonarr_tag=latest

Nothing is built server side for the build tag (and it's not meant to be) the building is happening on your system so if you're getting an old parent container is something on your end. You might be using a cached container or something. Maybe try wiping any old parent images you have and rebuilding?
