### ISSUE TITLE
SMA Config not abiding by environmental variables

### ISSUE THREAD

**Issue by JordMonte512** [mdhiggins/sonarr-sma#47]
Set up my docker container with instructions listed in the docker-hub and github information, however it appears that the SMA part that is integrating into the linuxserver sonarr container is not following the set environmental values as expected (PUID and PGID). 

Tested this on two different servers, locations and same outcome.

**Comment by mdhiggins** [comment]
Could you share your container config and test methodology?

The UID/GID stuff is all inherited from the parent linuxserver container the SMA layer doesn't do anything to modify it

**Comment by JordMonte512** [comment]
Can confirm it was human error.

Once I decided to stop being stupid, it worked.

Thank you anyway, and thank you for your quick reply!
