### ISSUE TITLE
ffmpeg can't be found

### ISSUE THREAD

**Issue by powerdude** [mdhiggins/sonarr-sma#5]
Hi,

after some recent updates, i now get error about the location of ffmpeg:

  | Component | Message | Time
-- | -- | -- | --
  | python3 | converter.ffmpeg.FFMpegError: ffmpeg binary not found: /usr/local/bin/ffmpeg/ffmpeg | Yesterday
  | python3 | raise FFMpegError("ffmpeg binary not found: " + self.ffmpeg_path) | Yesterday
  | python3 | File "/usr/local/bin/sma/sickbeard_mp4_automator/converter/ffmpeg.py", line 410, in __init__ | Yesterday
  | python3 | ffprobe_path=ffprobe_path) | Yesterday
  | python3 | File "/usr/local/bin/sma/sickbeard_mp4_automator/converter/__init__.py", line 27, in __init__ | Yesterday
  | python3 | self.converter = Converter(settings.ffmpeg, settings.ffprobe) | Yesterday
  | python3 | File "/usr/local/bin/sma/sickbeard_mp4_automator/mkvtomp4.py", line 29, in __init__ | Yesterday
  | python3 | converter = MkvtoMp4(settings) | Yesterday
  | python3 | File "/usr/local/bin/sma/sickbeard_mp4_automator/postSonarr.py", line 30, in <module> | Yesterday
  | python3 | Traceback (most recent call last): | Yesterday
  | python3 | converter.ffmpeg.FFMpegError: ffmpeg binary not found: /usr/local/bin/ffmpeg/ffmpeg | Yesterday
  | python3 | raise FFMpegError("ffmpeg binary not found: " + self.ffmpeg_path) | Yesterday
  | python3 | File "/usr/local/bin/sma/sickbeard_mp4_automator/converter/ffmpeg.py", line 410, in __init__ | Yesterday
  | python3 | ffprobe_path=ffprobe_path) | Yesterday
  | python3 | File "/usr/local/bin/sma/sickbeard_mp4_automator/converter/__init__.py", line 27, in __init__ | Yesterday
  | python3 | self.converter = Converter(settings.ffmpeg, settings.ffprobe) | Yesterday
  | python3 | File "/usr/local/bin/sma/sickbeard_mp4_automator/mkvtomp4.py", line 29, in __init__ | Yesterday
  | python3 | converter = MkvtoMp4(settings) | Yesterday
  | python3 | File "/usr/local/bin/sma/sickbeard_mp4_automator/postSonarr.py", line 30, in <module> | Yesterday
  | python3 | Traceback (most recent call last): | Yesterday
  | python3 | converter.ffmpeg.FFMpegError: ffmpeg binary not found: /usr/local/bin/ffmpeg/ffmpeg | Yesterday
  | python3 | raise FFMpegError("ffmpeg binary not found: " + self.ffmpeg_path) | Yesterday
  | python3 | File "/usr/local/bin/sma/sickbeard_mp4_automator/converter/ffmpeg.py", line 410, in __init__ | Yesterday
  | python3 | ffprobe_path=ffprobe_path) | Yesterday
  | python3 | File "/usr/local/bin/sma/sickbeard_mp4_automator/converter/__init__.py", line 27, in __init__ | Yesterday
  | python3 | self.converter = Converter(settings.ffmpeg, settings.ffprobe) | Yesterday
  | python3 | File "/usr/local/bin/sma/sickbeard_mp4_automator/mkvtomp4.py", line 29, in __init__ | Yesterday
  | python3 | converter = MkvtoMp4(settings) | Yesterday
  | python3 | File "/usr/local/bin/sma/sickbeard_mp4_automator/postSonarr.py", line 30, in <module> | Yesterday
  | python3 | Traceback (most recent call last): | Yesterday
  | python3 | converter.ffmpeg.FFMpegError: ffmpeg binary not found: /usr/local/bin/ffmpeg/ffmpeg | Yesterday
  | python3 | raise FFMpegError("ffmpeg binary not found: " + self.ffmpeg_path) | Yesterday
  | python3 | File "/usr/local/bin/sma/sickbeard_mp4_automator/converter/ffmpeg.py", line 410, in __init__ | Yesterday
  | python3 | ffprobe_path=ffprobe_path) | Yesterday
  | python3 | File "/usr/local/bin/sma/sickbeard_mp4_automator/converter/__init__.py", line 27, in __init__ | Yesterday
  | python3 | self.converter = Converter(settings.ffmpeg, settings.ffprobe) | Yesterday
  | python3 | File "/usr/local/bin/sma/sickbeard_mp4_automator/mkvtomp4.py", line 29, in __init__ | Yesterday
  | python3 | converter = MkvtoMp4(settings) | Yesterday
  | python3 | File "/usr/local/bin/sma/sickbeard_mp4_automator/postSonarr.py", line 30, in <module> | Yesterday
  | python3 | Traceback (most recent call last): | Yesterday
  | python3 | converter.ffmpeg.FFMpegError: ffmpeg binary not found: /usr/local/bin/ffmpeg/ffmpeg | Yesterday
  | python3 | raise FFMpegError("ffmpeg binary not found: " + self.ffmpeg_path) | Yesterday
  | python3 | File "/usr/local/bin/sma/sickbeard_mp4_automator/converter/ffmpeg.py", line 410, in __init__ | Yesterday
  | python3 | ffprobe_path=ffprobe_path) | Yesterday
  | python3 | File "/usr/local/bin/sma/sickbeard_mp4_automator/converter/__init__.py", line 27, in __init__ | Yesterday
  | python3 | self.converter = Converter(settings.ffmpeg, settings.ffprobe) | Yesterday

**Comment by mdhiggins** [comment]
The path was updated its /usr/local/bin/ffmpeg and /usr/local/bin/ffprobe no subdirectory

Though it should automatically update your autoProcess.ini file if the container has write permissions (make sure you’re using the latest container as I made some updates yesterday)

**Comment by powerdude** [comment]
I noticed the change and updated it manually.  i believe it does have write permissions but it wasn't updated.
