### ISSUE TITLE
Enhancement Request: Vaapi support

### ISSUE THREAD

**Issue by Muckoma** [mdhiggins/sonarr-sma#52]
Hi, Mdhiggins, 
I ran across this docker container while updating yours. Any thoughts about adding support for this in your container as well? It seems like it allows it to use vaapi which helps with hardware acceleration. 

https://registry.hub.docker.com/r/eikowagenknecht/sonarr-sma-vaapi/

Thanks

**Comment by Muckoma** [comment]
EDIT: I see it's supported but have to mount the device. Will do a bit of digging and report back. Trying to get this running on my synology 918+

**Comment by mdhiggins** [comment]
VAAPI fully supported already
