### ISSUE TITLE
ffmpeg and ffprobe don't work since update to Sonarr 4

### ISSUE THREAD

**Issue by mtrolley** [mdhiggins/sonarr-sma#54]
I updated my sonarr-sma container today and now post-processing fails:
```
root@docker:/usr/local/sma/config# tail sma.log
  File "/usr/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/bin/ffprobe'
2024-01-01 12:37:59 - resources.mediaprocessor - INFO - File /storage/plex/TV/... is not valid
2024-01-01 12:37:59 - SonarrPostProcess - ERROR - Processing returned False.
2024-01-01 12:37:59 - SonarrPostProcess - ERROR - Error processing file.
Traceback (most recent call last):
  File "/usr/local/sma/postSonarr.py", line 230, in <module>
    sys.exit(1)
SystemExit: 1
```

```
root@docker:/usr/local/sma/config# /usr/local/bin/ffprobe
bash: /usr/local/bin/ffprobe: cannot execute: required file not found
root@docker:/usr/local/sma/config# /usr/local/bin/ffmpeg
bash: /usr/local/bin/ffmpeg: cannot execute: required file not found
```

**Comment by mtrolley** [comment]
I think the issue is that they switched from Ubuntu to Alpine for the base image:

> 30.12.23: - Rebase master branch to Alpine 3.19.

https://hub.docker.com/r/linuxserver/sonarr

**Comment by mdhiggins** [comment]
Just rebased this container as well to match, try and do a fresh pull and see if its working

**Comment by mtrolley** [comment]
I'll try shortly.

I think more needs to be done though, right? For example this script tries to install packages using APT which won't work now: https://github.com/mdhiggins/sonarr-sma/blob/master/root/etc/s6-overlay/s6-rc.d/init-sma-config/run

**Comment by mdhiggins** [comment]
Nope should be good. That script has an if statement to work on both. The develop tag has been on alpine now for like a year so I just had to migrate that over

**Comment by mtrolley** [comment]
It's working, thanks so much!
