### ISSUE TITLE
Unknown Encoder 'h264_nvenc'

### ISSUE THREAD

**Issue by Kieranwest** [mdhiggins/sonarr-sma#61]
Hi, 
Not sure if I'm missing something but really trying my best to get this to work. I want to avoid using CPU for encoding and I have a 1070 available in my server. It works great for all other docker containers, Plex, Ollama, unmanic. However, I cannot for the life of me get it working with Sonarr-SMA and Radarr-SMA. 

When attempting to run `ffmpeg -y -vsync 0 -hwaccel cuda -hwaccel_output_format cuda -i input.avi -c:a copy -c:v h264_nvenc -b:v 5M output.mp4` as found [here on FFMPEGs website](https://docs.nvidia.com/video-technologies/video-codec-sdk/12.0/ffmpeg-with-nvidia-gpu/index.html#hwaccel-transcode-without-scaling). I get an error stating the encoder is not found. 

My container has --runtime=nvidia and --gpus=all within the extra parameters on unRAID. 
Not sure if this is just not supported by the container? 
Any help would be greatly appreciated, I've been at this for weeks.

**Comment by mdhiggins** [comment]
The ffmpeg build included does not have nvenc and due to linuxserver moving the parent containers to alpine Linux I don't believe a compatible version of ffmpeg exists at this time that supports both nvenc and alpine

**Comment by Kieranwest** [comment]
Thanks for getting back to me. I'll try switching over to unmanic, I know that has a build of FFMPEG that works and has an SMA script. 
Would this config supposedly work? 
Their built in nvenc encoder works but when I use it with SMA it always does CPU encoding :(
```
[Converter]
ffmpeg = ffmpeg
ffprobe = ffprobe
threads = 0
hwaccels = cuda, nvenc, cuvid
hwaccel-decoders = h264_cuda, hevc_cuvid, h264_cuvid
hwdevices = cuda:0
hwaccel-output-format = cuda:cuvid
output-directory = 
output-format = mp4
output-extension = mp4
temp-extension = .sma
minimum-size = 0
ignored-extensions = nfo, ds_store
copy-to = 
move-to = 
delete-original = True
sort-streams = True
process-same-extensions = True
bypass-if-copying-all = False
force-convert = True
post-process = False
wait-post-process = False
detailed-progress = False
opts-separator = ,
preopts = 
postopts = 
regex-directory-replace = [^\w\-_\. ]
```

**Comment by mdhiggins** [comment]
Looks good. You'll also want to set your encoder under the video section
