### ISSUE TITLE
kubernetes permissions issues

### ISSUE THREAD

**Issue by tscibilia** [mdhiggins/sonarr-sma#64]
I'm a long-time user of your containers, thank you for all the work and support you put into it. I used to run this on docker but recently switched to a k3s cluster. I know you said in a previous issue that you're not looking to move away from the linuxserver base images but is there a simple way to make the container rootless like the user [onedr0p does here](https://github.com/onedr0p/containers/blob/main/apps/sonarr/Dockerfile)?

It seems that even though I set the PUID and GUID in the environment variables, the container wants to run as a root user and it's not performing the same as it did when I ran it on docker. Most errors are `Failed to get runtime from the file, make sure ffprobe is available`, but it also has errors writing sma.log 

I totally understand if you don't want to support this, if not do you have any other ideas? My knowledge of kubernetes is limited, but I was considering running a sidecar container that fixes the permissions, I also considered trying to combine your dockerfile with the onedr0p one (but I admittedly know even less about doing that, so my last option might be using tdarr if all else fails.

**Comment by tscibilia** [comment]
Actually, I take that back. It might have just been a few files that were giving me repeating errors. I'll keep an eye on it and try to clean up my queue to see if it's processing requests correctly. I looked back at my original docker container and all of the permissions seem to be the same. So I'm not sure why I was seeing so many errors.

**Comment by mdhiggins** [comment]
I don't believe the containers should require root but keep me posted

**Comment by tscibilia** [comment]
I'm not entirely sure what the issue was that I had been getting errors for (my best guess at the ffprobe error was that there were special characters in the file name like Shōgun and I'm still not sure how to sanitize those filenames automatically). However, I'm not getting the sma log error anymore I realized that my autoProcess.ini permission was accidentally set to 644 and not 664.  

However, I'm getting this error `Unable to send OnDownload notification to: SMAv3: An error occurred trying to start process '/usr/local/sma/postSonarr.sh' with working directory '/app/sonarr/bin'. Permission denied` 
postSonarr.sh is owned by abc:abc, the directory /app/sonarr/bin is owned by root:root, and the contents of that directory is owned by 1001:127
