### ISSUE TITLE
sma.log default permission

### ISSUE THREAD

**Issue by jpcastberg** [mdhiggins/sonarr-sma#65]
Hey, I just set this up and wasn't able to get sonarr to run the script successfully until I gave global write permissions to the log file.

Permissions before change:
```
-rw-r--r-- 1 root root 9618 Nov 16 10:14 /usr/local/sma/config/sma.log
```

Error:
```
[Error] postSonarr.sh: PermissionError: [Errno 13] Permission denied: '/usr/local/sma/config/sma.log'
```

Fix:
```
chmod a+w /usr/local/sma/config/sma.log
```

**Comment by mdhiggins** [comment]
Global write permission shouldn't be required, but since the log files are in a mounted volume if you had incompatible permissions this might be a workaround

Whatever user you're using for PUID or PGID just needs write permissions

**Comment by mdhiggins** [comment]
![image](https://github.com/user-attachments/assets/b46bc2d2-97f5-4a44-85db-2a9f7ec5360f)

Screenshot of my sma directory, with dockeruser:dockeruser ID's being my PUID:PGID respectively

**Comment by jpcastberg** [comment]
@mdhiggins I think I see what went wrong - my first run of sma on the container was manually done via manual.py as root. this caused the log file to be created as root with the default root permissions (`-rw-r--r--`).

Then, when I went to go setup the connection in sonarr and tried to test, it ran as the container user which didn't have permissions to write to the log file. So, user error! Thank you for your quick reply though :)
